#!/usr/bin/env bash
# Bash script that will display information about subdomains.

sub_domains () {
        if [ "$#" -eq 2 ]; then
                rec=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline; print $4}')
                dest=$(dig $2.$1 | awk '/ANSWER SECTION:/ {getline; print $5}')
                echo "The subdomain $2 is a $rec record and points to $dest"
        elif [ "$#" -eq 1 ]; then
                rec=$(dig $1 | awk '/ANSWER SECTION:/ {getline; print $4}')
                dest=$(dig $1 | awk '/ANSWER SECTION:/ {getline; print $5}')
                for sub in "www" "lb-01" "web-01" "web-02"; do
                        rec=$(dig $1| awk '/ANSWER SECTION:/ {getline; print $4}')
                        dest=$(dig $sub.$1 | awk '/ANSWER SECTION:/ {getline; print $5}')
                        echo "The subdomain $sub is a $rec record and points to $dest"
                done
        fi
}
sub_domains $1 $2
