#!/usr/bin/env bash                                                                                                             
# Install nginx on your web-01 and Configure your Nginx server                                                                  
#to have a custom 404 page that contains the string Ceci n'est pas une page.                                                    #and  HTTP response contains a custom header
                                                                                                                                
sudo apt-get -y update                                                                                                          
sudo apt-get -y install nginx                                                                                                   
sudo ufw allow 'Nginx HTTP'                                                                                                     
echo "Hello World!" | sudo tee /var/www/html/index.html                                                                         
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/ngi
nx/sites-available/default                                                                                                      
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my_404.html                                                     
sudo sed -i '/server_name _;/a error_page 404 /my_404.html;\nlocation = /my_404.html {root /usr/share/nginx/html; internal; }' /
etc/nginx/sites-available/default                                                                                               
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By \"$HOSTNAME\";' /etc/nginx/sites-available/default             
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/                                                        
sudo service nginx restart

