#!/usr/bin/env bash
# Bash script that configures a server to listen on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo swd -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx start

