#!/usr/bin/env bash
#configurations to run Nginx as nginx
pkill apache2
chown -R nginx /etc/nginx
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -l -u nginx service nginx restart

